import type { AppState, HookDockBridge, HookEvent } from "./types";

const now = Date.now();

const demoEvents: HookEvent[] = [
  {
    id: "demo-approval",
    source: "claude",
    providerName: "Claude Code",
    eventType: "PermissionRequest",
    sessionKey: "claude:demo",
    project: "hookdock",
    cwd: "C:\\workspace\\hookdock",
    title: "Claude Code requests PowerShell",
    body: "npm run check",
    status: "waitingApproval",
    toolName: "PowerShell",
    questions: [],
    expectsResponse: true,
    shouldNotify: true,
    receivedAt: new Date(now - 18_000).toISOString(),
  },
  {
    id: "demo-complete",
    source: "codex",
    providerName: "Codex",
    eventType: "Stop",
    sessionKey: "codex:demo",
    terminalTarget: {
      kind: "hookdockTerminal",
      sessionId: "7f6b3978-25f1-4519-8b02-8fe67f35991f",
      protocol: 1,
    },
    project: "desktop-client",
    title: "Codex completed the task",
    body: "The Windows hook integration is ready",
    status: "completed",
    questions: [],
    expectsResponse: false,
    shouldNotify: true,
    receivedAt: new Date(now - 44_000).toISOString(),
  },
  {
    id: "demo-input",
    source: "gemini",
    providerName: "Gemini CLI",
    eventType: "Notification",
    sessionKey: "gemini:demo",
    project: "web-app",
    title: "Gemini CLI is waiting for input",
    body: "Return to the terminal to continue",
    status: "waitingInput",
    questions: [],
    expectsResponse: false,
    shouldNotify: true,
    receivedAt: new Date(now - 72_000).toISOString(),
  },
];

export const demoState: AppState = {
  listening: true,
  compact: false,
  port: 37_129,
  events: demoEvents,
  pendingEventIds: ["demo-approval"],
  selectedEventId: "demo-approval",
  settings: {
    notificationsEnabled: true,
    showPanelOnAttention: true,
    openAtLogin: true,
    playSound: true,
    language: "auto",
  },
  sourceProfiles: [
    { id: "claude", name: "Claude Code", icon: "C", accentColor: "#d97757", showToast: true, playSound: true, autoExpand: true, enabled: true },
    { id: "codex", name: "Codex", icon: "⌁", accentColor: "#22c55e", showToast: true, playSound: true, autoExpand: true, enabled: true },
    { id: "gemini", name: "Gemini CLI", icon: "✦", accentColor: "#8b5cf6", showToast: true, playSound: true, autoExpand: true, enabled: true },
    { id: "generic", name: "Custom Hook", icon: "⚓", accentColor: "#22d3ee", showToast: true, playSound: true, autoExpand: true, enabled: true },
  ],
  hookStatus: {
    claude: { title: "Claude Code", installed: true, filePath: "%USERPROFILE%\\.claude\\settings.json" },
    codex: { title: "Codex", installed: true, filePath: "%USERPROFILE%\\.codex\\hooks.json" },
    gemini: { title: "Gemini CLI", installed: false, filePath: "%USERPROFILE%\\.gemini\\settings.json" },
  },
  genericCommand: '"C:\\Program Files\\HookDock\\resources\\bridge\\hookdock-hook.exe" --source generic',
  platform: "win32",
  version: "0.1.0",
};

export const demoBridge: HookDockBridge = {
  async getState() { return demoState; },
  onState() { return () => undefined; },
  async respond() { return { ok: true }; },
  async dismissEvent() { return { ok: true }; },
  async focusEventTerminal() { return { ok: true }; },
  async updateSettings(patch) { return { ...demoState.settings, ...patch }; },
  async updateSourceProfile(id, patch) { return demoState.sourceProfiles.map((profile) => profile.id === id ? { ...profile, ...patch } : profile); },
  async installHooks() { return { ok: true }; },
  async uninstallHooks() { return { ok: true }; },
  async copyGenericCommand() { return { ok: true }; },
  async sendTestEvent() { return { ok: true }; },
  async openFolder() { return { ok: true }; },
  async openUrl() { return { ok: true }; },
  async setCompact() { return { ok: true }; },
  async snapWindow() { return { ok: true }; },
  hideWindow() {},
};
